seed: 0
task: "set_table"
policy_type: "rl_per_obj"  # or "rl_all_obj" depending on your policies
max_trajectories: 100  # or however many episodes you want to evaluate
save_trajectory: false

eval_env:
  make_env: true
  env_id: "SequentialTask-v0"
  num_envs: 63  # parallel envs
  max_episode_steps: 500
  
  continuous_task: false
  cat_state: true
  cat_pixels: false
  frame_stack: 3
  
  stationary_base: false
  stationary_torso: false
  stationary_head: true
  
  # navigate-only task plans
  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/navigate/train/all.json
  
  record_video: true
  info_on_video: true
  
  env_kwargs:
    require_build_configs_repeated_equally_across_envs: false

logger:
  workspace: "mshab_exps"
  exp_name: "eval/set_table/navigate/train"
  clear_out: true
  tensorboard: false
  wandb: false